# Generated by Django 4.2.1 on 2023-06-10 00:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='link',
            field=models.TextField(default='www.flipkart.com'),
            preserve_default=False,
        ),
    ]
