# Generated by Django 4.2.1 on 2023-06-13 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_product_created_at_product_updated_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='overall_ratings',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='product',
            name='ratings',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='product',
            name='reviews',
            field=models.IntegerField(),
        ),
    ]
