# Generated by Django 4.2.1 on 2023-06-08 11:47

from django.db import migrations, models

class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=5000)),
                ('price', models.TextField()),
                ('ratings', models.TextField()),
                ('reviews', models.TextField()),
                ('overall_ratings', models.TextField()),
            ],
        ),
    ]
