# Generated by Django 4.2.1 on 2023-06-10 01:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_product_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='img_link',
            field=models.TextField(default='https://st4.depositphotos.com/14953852/22772/v/600/depositphotos_227725020-stock-illustration-image-available-icon-flat-vector.jpg'),
            preserve_default=False,
        ),
    ]
