# Generated by Django 4.2.1 on 2023-07-10 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_product_query'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='nrating',
            field=models.IntegerField(default=80),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='prating',
            field=models.IntegerField(default=20),
            preserve_default=False,
        ),
    ]
